export { HeroSection } from './HeroSection'
export { AboutSection } from './AboutSection'
export { ResumeSection } from './ResumeSection'
export { TechStackSection } from './TechStackSection'
export { PortfolioSection } from './PortfolioSection'
export { ImpactSection } from './ImpactSection'
export { ContactSection } from './ContactSection'
